name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0
        id: release
        with:
          release-type: simple
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        if: ${{ steps.release.outputs.release_created }}
        with:
          fetch-depth: 0
      - name: Setup deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        if: ${{ steps.release.outputs.release_created }}
      - name: Bump up jsr.json
        run: deno run --allow-write --allow-read internal/bumpup.ts jsr.json --next ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
        if: ${{ steps.release.outputs.release_created }}
      - name: Upload Release Artifact
        run: deno publish --allow-dirty --config jsr.json
        if: ${{ steps.release.outputs.release_created }}

